
  <!-- Begin Page Content -->
  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Purchase Order #<?php echo $this->escapehtml($this->purchaseOrder->getId()); ?></h1>
    </div>

    <?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
')
->setMessageSeparatorString('')
->setMessageCloseString('</div>');

echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

    <!-- Content Row -->
    <div class="row">

      <!-- Content Column -->
      <div class="col-lg-4 mb-4">

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Requested Details</h6>
          </div>
          <div class="card-body">
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-4 col-form-label">Requested By</label>
              <div class="col-sm-8">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo $this->escapehtml($this->createdBy->getFirstName()); ?> <?php echo $this->escapehtml($this->createdBy->getLastName()); ?>">
              </div>
            </div>
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-4 col-form-label">Requested Datetime</label>
              <div class="col-sm-8">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo date('M d, Y H:i:s', strtotime($this->createdBy->getCreatedDatetime())); ?>">
              </div>
            </div>

            <table class="table table-striped table-bordered table-hover table-sm">
              <thead>
                <tr>
                  <th scope="col">Item</th>
                  <th scope="col">Quanitity</th>
                  <th scope="col">Standard Rate (PHP)</th>
                </tr>
              </thead>
              <tbody>
                <?php
                  $standardRateTotal = 0;
                  foreach ($this->purchaseOrderItems as $row):
                    $standardRateSubTotal = $row->getQuantity() * $row->getUnitPrice();
                    $standardRateTotal += $standardRateSubTotal;
                ?>
                <tr>
                  <td><?php echo $this->escapehtml($row->getItem()); ?></td>
                  <td><?php echo $this->escapehtml($row->getQuantity()); ?></td>
                  <td>PHP <?php echo $this->escapehtml($row->getUnitPrice()); ?></td>
                </tr>
                <?php endforeach; ?>
              </tbody>
            </table>
            <h3 id="total" class="float-right">Total: PHP <?php echo number_format($standardRateTotal, 2, '.', ' '); ?></h3>
            <div class="clearfix"></div>

          </div>
        </div>

      </div>

      <div class="col-lg-8 mb-7">

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Bidders/Suppliers/Vendors</h6>
          </div>
          <div class="card-body">
            <form id="myForm" method="post">
            <table class="table table-striped table-bordered table-hover table-sm">
              <thead>
                <tr>
                  <th>Company Name</th>
                  <th>Quotation</th>
                  <th>Details</th>
                  <th>Requestor</th>
                  <th>Operation Dept.</th>
                  <th>Finance Dept.</th>
                </tr>
              </thead>
              <tbody>
                <?php
                  $ctr = 0;
                  foreach ($this->purchaseOrderItemBids as $row):
                    $ctr++;
                ?>
                <tr>
                  <td><a href="#"><?php echo $this->escapehtml($row->company_name); ?></a></td>
                  <td>PHP <?php echo number_format($row->amount, 2, '.', ' '); ?></td>
                  <td><a href="#">Details</a></td>
                  <td class="text-center"><?php if($ctr==1): ?><i class="fas fa-thumbs-up"></i><?php else: ?><i class="fas fa-minus-circle"></i><?php endif; ?></td>
                  <td class="text-center"><?php if($ctr==1): ?><i class="fas fa-thumbs-up"></i><?php else: ?><i class="fas fa-minus-circle"></i><?php endif; ?></td>
                  <td class="text-center"><button type="button" class="myButton" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-thumbs-up" style="color:green"></i></button> | <button data-toggle="modal" data-target="#exampleModal" type="button" class="myButton"><i class="fas fa-thumbs-down" style="color:red"></i></button> </td>
                </tr>
                <?php endforeach; ?>
              </tbody>
            </table>
          </form>
          </div>
        </div>

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Finance Department</h6>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-3">
                <img src="<?php echo $this->getQRCode($this->escapehtml($this->user->getPublicAddress()), 200, 200); ?>">
              </div>
              <div class="col-lg-9">
                <p><strong>User: </strong><?php echo $this->escapehtml($this->user->getFirstName()); ?> <?php echo $this->escapehtml($this->user->getLastName()); ?></p>
                <p><strong>My Public Address: </strong><?php echo $this->escapehtml($this->user->getPublicAddress()); ?></p>
                <p><strong>Funds: PHP 100,000.00</strong></p>
                <p><strong>Blockchain Explorers: </strong> <a href="https://eosauthority.com/" target="_blank">Open</a></p>
              </div>
          </div>
        </div>

      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

  <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Approved Bid</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><strong>PO#19</strong> Bid/Quotation Approved for Supplier/Vendor Electro Works.</p>
        <p><strong>Electro Works Public Address:</strong> 1ABS4s1TzPn8fR7WG6tZWu4TSPAMeBUeuVML8Q</p>
        <img src="<?php echo $this->getQRCode($this->escapehtml($this->user->getPublicAddress()), 200, 200); ?>">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Approved Bid</button>
      </div>
    </div>
  </div>
</div>

  <script>
  $(document).ready(function(){
    $(".myButton").click(function() {
      return signin();
    });
    $(".myForm").submit(function() {
      return signin();
    });
  });
  </script>
