
  <!-- Begin Page Content -->
  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Purchase Order #<?php echo $this->escapehtml($this->purchaseOrder->getId()); ?></h1>
    </div>

    <!-- Content Row -->
    <div class="row">

      <!-- Content Column -->
      <div class="col-lg-6 mb-4">

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Requested Details</h6>
          </div>
          <div class="card-body">
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-4 col-form-label">Requested By</label>
              <div class="col-sm-8">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo $this->escapehtml($this->createdBy->getFirstName()); ?> <?php echo $this->escapehtml($this->createdBy->getLastName()); ?>">
              </div>
            </div>
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-4 col-form-label">Requested Datetime</label>
              <div class="col-sm-8">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo date('M d, Y', strtotime($this->createdBy->getCreatedDatetime())); ?>">
              </div>
            </div>
          </div>
        </div>

      </div>

      <div class="col-lg-6 mb-4">

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Supplier/Vendor Company</h6>
          </div>
          <div class="card-body">
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-4 col-form-label">Company Name</label>
              <div class="col-sm-8">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo $this->escapehtml($this->supplier->getCompanyName()); ?>">
              </div>
            </div>
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-4 col-form-label">Company Address</label>
              <div class="col-sm-8">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo $this->escapehtml($this->supplier->getCompanyAddress()); ?>">
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-12">
        <!-- Approach -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Bid/Quotation</h6>
          </div>
          <div class="card-body">
            <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>

            <form method="post">
              <div class="form-group">
                <?php
                  $standardRateTotal = 0;
                  foreach ($this->purchaseOrderItems as $row):
                    $standardRateSubTotal = $row->getQuantity() * $row->getUnitPrice();
                    $standardRateTotal += $standardRateSubTotal;
                ?>
                <div class="form-row">
                  <div class="form-group col-md-3">
                    <label for="inputEmail4">Item Name</label>
                    <input type="text" class="form-control item" readonly name="items[]" value="<?php echo $this->escapehtml($row->getItem()); ?>">
                  </div>
                  <div class="form-group col-md-2">
                    <label for="inputEmail4">Quantity</label>
                    <input type="text" class="form-control quantity" name="quanitities[]" readonly value="<?php echo $this->escapehtml($row->getQuantity()); ?>">
                  </div>
                  <div class="form-group col-md-2">
                    <label for="inputEmail4">Standard Rate (PHP)</label>
                    <input type="text" class="form-control standard_rate" readonly name="standard_rate[]" value="<?php echo $this->escapehtml($row->getUnitPrice()); ?>">
                  </div>
                  <div class="form-group col-md-2">
                    <label for="inputEmail4">My Price (PHP)</label>
                    <input type="text" class="form-control price" placeholder="Unit Price" name="prices[]" value="0.00">
                  </div>
                  <div class="form-group col-md-3">
                    <label for="inputEmail4">Total</label>
                    <input type="text" class="form-control subtotal" placeholder="Total" readonly value="0.00">
                  </div>
                </div>
              <?php endforeach; ?>
                <h3 id="standard_rate_total" class="float-left">Standard Rate Total: PHP <?php echo number_format($standardRateTotal, 2, '.', ' '); ?></h3><div class="clearfix"></div>
                <h3 id="total" class="float-right">My Bid Total: PHP 0.00</h3>
                <div class="clearfix"></div>
              </div>

              <div class="form-group">
                <label for="comments">Comments</label>
                <textarea class="form-control" name="comments" id="comments" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

  <script>

  $(document).ready(function() {
    $.fn.inputFilter = function(inputFilter) {
      return this.on("input keydown keyup mousedown mouseup select contextmenu drop", function() {
        if (inputFilter(this.value)) {
          this.oldValue = this.value;
          this.oldSelectionStart = this.selectionStart;
          this.oldSelectionEnd = this.selectionEnd;
        } else if (this.hasOwnProperty("oldValue")) {
          this.value = this.oldValue;
          this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
        }
      });
    };

    function getTotal(){
      var total = 0;
      $(".item").each(function(){
        var quantity = $(this).closest('.form-row').find('.quantity').val();
        var price = $(this).closest('.form-row').find('.price').val();
        var subtotal = price * quantity;
        total += subtotal;
      });

      $("#total").html("My Bid Total: PHP " + parseFloat(Math.round(total * 100) / 100).toFixed(2));
    }

    // Restrict input to digits by using a regular expression filter.
    $(".price").inputFilter(function(value) {
      return /^\d*$/.test(value);
    });

    $(".quantity").on("input keydown keyup mousedown mouseup select contextmenu drop", function() {
      var price = $(this).closest('.form-row').find('.price').val();
      var quantity = $(this).val();
      var total = price * quantity;
      $(this).closest('.form-row').find('.subtotal').val(parseFloat(Math.round(total * 100) / 100).toFixed(2));
      getTotal();
    });

    $(".price").on("input keydown keyup mousedown mouseup select contextmenu drop", function() {
      var quantity = $(this).closest('.form-row').find('.quantity').val();
      var price = $(this).val();
      var total = price * quantity;
      $(this).closest('.form-row').find('.subtotal').val(parseFloat(Math.round(total * 100) / 100).toFixed(2));
      getTotal();
    });
  });
  </script>
