
  <!-- Begin Page Content -->
  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Meeting</h1>
    </div>


    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-12">
        <!-- Approach -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Channel General</h6>
          </div>
          <div class="card-body">
            <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>

     <center>
     <div id="otEmbedContainer" style="width:800px; height:640px"></div>
                   <script src="https://tokbox.com/embed/embed/ot-embed.js?embedId=7bedc874-4d64-41b1-b53d-db4a26bd3971&room=DEFAULT_ROOM"></script>
                 </center>
          </div>
        </div>

      </div>
    </div>

  </div>
  <!-- /.container-fluid -->
