
  <!-- Begin Page Content -->
  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Meeting</h1>
    </div>


    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-12">
        <!-- Approach -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Video Conference</h6>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-4 mb-4">
                <!-- Approach -->
                <div class="card shadow mb-4">
                  <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Channel General</h6>
                  </div>
                  <div class="card-body text-center">
                    <a href="<?php echo $this->url('meeting', ['action' => 'channel']); ?>"><img src="/img/video-conference.png"></a>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mb-4">
                <!-- Approach -->
                <div class="card shadow mb-4">
                  <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Channel Finance Dept.</h6>
                  </div>
                  <div class="card-body text-center">
                    <a href="<?php echo $this->url('meeting', ['action' => 'channel']); ?>"><img src="/img/u_finance.jpg"></a>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mb-4">
                <!-- Approach -->
                <div class="card shadow mb-4">
                  <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Channel Operation Dept.</h6>
                  </div>
                  <div class="card-body text-center">
                    <a href="<?php echo $this->url('meeting', ['action' => 'channel']); ?>"><img src="/img/video-conference.png"></a>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mb-4">
                <!-- Approach -->
                <div class="card shadow mb-4">
                  <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Channel Engineers</h6>
                  </div>
                  <div class="card-body text-center">
                    <a href="<?php echo $this->url('meeting', ['action' => 'channel']); ?>"><img src="/img/video-conference.png"></a>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mb-4">
                <!-- Approach -->
                <div class="card shadow mb-4">
                  <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Top Management</h6>
                  </div>
                  <div class="card-body text-center">
                    <a href="<?php echo $this->url('meeting', ['action' => 'channel']); ?>"><img src="/img/video-conference.png"></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
  <!-- /.container-fluid -->
