<!-- Outer Row -->
<div class="row justify-content-center">

  <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-6 d-none d-lg-block bg-login-image">
            <a href="<?php echo $this->url('home'); ?>"><img src="/img/ulisplash.jpg"></a>
          </div>
          <div class="col-lg-6">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">ULI PH e-Procurement</h1>
              </div>
              <?php
              $form->setAttribute('action', $this->url('home'));
              $form->setAttribute('name', 'login');
              $form->setAttribute('class', 'user');
              $form->prepare();
              echo $this->form()->openTag($form);
              ?>
                <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    ')
                    ->setMessageSeparatorString('')
                    ->setMessageCloseString('</div>');

                echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                 ?>

                <div class="form-group">
                  <?= $this->formElement($form->get('email')) ?>
                  <?= $this->formElementErrors()->render($form->get('email'), ['class' => 'help-block']) ?>
                </div>
                <div class="form-group">
                  <?= $this->formElement($form->get('password')) ?>
                  <?= $this->formElementErrors()->render($form->get('password'), ['class' => 'help-block']) ?>
                </div>
                <div class="form-group">
                  <div class="custom-control custom-checkbox small">
                    <?= $this->formElement($form->get('remember_me')); ?>
                    <label class="custom-control-label" for="customCheck">Remember Me</label>
                  </div>
                </div>
                <?= $this->formElement($form->get('redirect_url')); ?>
                <?= $this->formElement($form->get('csrf')) ?>
                <?php echo $this->formSubmit($form->get('submit')); ?>
              <?php echo $this->form()->closeTag();?>
              <hr>
              <div class="text-center">
                <a class="small" href="#">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="<?php echo $this->url('registration'); ?>">Create an Account!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>
